syntax = "proto3";

package core;

import "google/protobuf/timestamp.proto";
import "Common/uuid.proto";

service ChatService {
    rpc initialize_chat (stream ChatServiceRequest) returns (stream ChatServiceEvent);
}

message ChatServiceRequest {
    oneof chat_service_request {
        InitMessage init_message = 1;
        Message message = 2;
    }
}

message InitMessage {
    string chat_name = 1;
}

message Message {
    common.Uuid uid = 1;
    string chat_name = 2;
    string message_text = 3;
    string sender_name = 4;
    google.protobuf.Timestamp message_send_time = 5;
}

message ChatServiceEvent {
    string chat_name = 1;
    repeated Message messages = 2;
}
