services:
  backend:
    build:
      context: ../
      dockerfile: docker/BackendApp.Dockerfile
    image: grpc-check-backend
    ports:
      - "8080:8080"
      - "8081:8081"
    profiles: [cli, react, backend] # запустится в любом из этих профилей

  cli:
    build:
      context: ../
      dockerfile: docker/FileManagerCliClient.Dockerfile
    image: grpc-check-cli
    depends_on:
      - backend
    environment:
      - GrpcServerUrl=http://backend:8080
    profiles: [cli]

  react:
    build:
      context: ../
      dockerfile: docker/FrontendApp.Dockerfile
    image: grpc-check-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_GRPC_URL=http://backend:8080
    profiles: [react]