/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
// noinspection JSUnusedGlobalSymbols
import { Route as rootRoute } from './routes/__root';
import { Route as FilesImport } from './routes/files';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const FilesRoute = FilesImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        '/files': {
            id: '/files';
            path: '/files';
            fullPath: '/files';
            preLoaderRoute: typeof FilesImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/files': typeof FilesRoute;
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/files': typeof FilesRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    '/': typeof IndexRoute;
    '/files': typeof FilesRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: '/' | '/files';
    fileRoutesByTo: FileRoutesByTo;
    to: '/' | '/files';
    id: '__root__' | '/' | '/files';
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    FilesRoute: typeof FilesRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    FilesRoute: FilesRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/files"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/files": {
      "filePath": "files.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
