# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatCore/chat_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ChatCore/chat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ..Common import uuid_pb2 as Common_dot_uuid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hatCore/chat_service.proto\x12\x04\x63ore\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11\x43ommon/uuid.proto\"y\n\x12\x43hatServiceRequest\x12)\n\x0cinit_message\x18\x01 \x01(\x0b\x32\x11.core.InitMessageH\x00\x12 \n\x07message\x18\x02 \x01(\x0b\x32\r.core.MessageH\x00\x42\x16\n\x14\x63hat_service_request\" \n\x0bInitMessage\x12\x11\n\tchat_name\x18\x01 \x01(\t\"\x99\x01\n\x07Message\x12\x19\n\x03uid\x18\x01 \x01(\x0b\x32\x0c.common.Uuid\x12\x11\n\tchat_name\x18\x02 \x01(\t\x12\x14\n\x0cmessage_text\x18\x03 \x01(\t\x12\x13\n\x0bsender_name\x18\x04 \x01(\t\x12\x35\n\x11message_send_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"F\n\x10\x43hatServiceEvent\x12\x11\n\tchat_name\x18\x01 \x01(\t\x12\x1f\n\x08messages\x18\x02 \x03(\x0b\x32\r.core.Message2V\n\x0b\x43hatService\x12G\n\x0finitialize_chat\x12\x18.core.ChatServiceRequest\x1a\x16.core.ChatServiceEvent(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatCore.chat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATSERVICEREQUEST']._serialized_start=89
  _globals['_CHATSERVICEREQUEST']._serialized_end=210
  _globals['_INITMESSAGE']._serialized_start=212
  _globals['_INITMESSAGE']._serialized_end=244
  _globals['_MESSAGE']._serialized_start=247
  _globals['_MESSAGE']._serialized_end=400
  _globals['_CHATSERVICEEVENT']._serialized_start=402
  _globals['_CHATSERVICEEVENT']._serialized_end=472
  _globals['_CHATSERVICE']._serialized_start=474
  _globals['_CHATSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
